version: '3.9'

services:
  web:
    build: .
    container_name: spotify_dash_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/spotify_db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: spotify_dash_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spotify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
